services:
  - type: web
    name: back
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here if needed
